{
  config,
  pkgs,
  lib,
  user,
  ...
}:

{
  # Bootloader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Networking
  networking.hostName = "box";
  networking.networkmanager.enable = true;
  networking.firewall.allowedTCPPorts = [ 22 ];

  # Locale and timezone
  time.timeZone = "Europe/London";
  i18n.defaultLocale = "en_GB.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_GB.UTF-8";
    LC_IDENTIFICATION = "en_GB.UTF-8";
    LC_MEASUREMENT = "en_GB.UTF-8";
    LC_MONETARY = "en_GB.UTF-8";
    LC_NAME = "en_GB.UTF-8";
    LC_NUMERIC = "en_GB.UTF-8";
    LC_PAPER = "en_GB.UTF-8";
    LC_TELEPHONE = "en_GB.UTF-8";
    LC_TIME = "en_GB.UTF-8";
  };

  # File systems
  fileSystems."/mnt/nvme" = {
    device = "/dev/nvme0n1p1";
    fsType = "ext4";
  };
  fileSystems."/mnt/lightroom" = {
    device = "/dev/nvme1n1p2";
    fsType = "ext4";
  };

  # X11 keymap
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # User configuration
  users.users.${user} = {
    isNormalUser = true;
    description = "Alexey Shekhirin";
    extraGroups = [
      "networkmanager"
      "wheel"
    ];
    packages = with pkgs; [ ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPW/RxwmcIDELwXMmja7fnzwIVTzIEDwqbqFSDDeCDHn shekhirin@shekhirin.local"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBe6TP7V6d9DEa6eTdBQCsSlVjr3cvhUyAUDeoGBTCfj Generated By Termius"
    ];
  };

  # Allow passwordless sudo for deployment
  security.sudo.wheelNeedsPassword = false;

  # System packages
  environment.systemPackages = with pkgs; [
    vim
    git
    ghostty.terminfo
  ];

  # Services
  services.openssh.enable = true;
  services.tailscale.enable = true;

  # Programs
  programs.mosh.enable = true;

  # Nix settings
  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  # State version
  system.stateVersion = "25.05";
}
